### ISSUE TITLE
address mapping problem in hwarch.html

### ISSUE THREAD

**Issue by xranger** [nvdla/nvdla.github.io#1] opened 2017-11-17 03:41 UTC
The address mapping in nvdla.github.io-master/hwarch.html#address-space-layout seems a lot of mis-match. 
1). Why each block has a 0x3000 offset compare to Table-10? 
2). Table-15 and Table-16 is the same? Should not be, right?

**Comment by jwise** [comment] 2017-11-18 01:23
Good catch.  I think the first part is the same problem as nvdla/doc#4.  I'll poke the reviewer on that change again :-)

The address offset on table 16 should be different, as you noted; @cliffgold fixed that, too.

I'll close this as a duplicate of that bug, but thank you for sending this in!

**Closed as completed by jwise** 2017-11-18 01:23 UTC

**Comment by HippieSavag3** [comment] 2019-08-25 06:33
Wtf
